### ISSUE TITLE
Crash after starting

### ISSUE THREAD

**Issue by swapnil-borade** [remear/jewelrybox#184] opened 2013-03-22 20:36 UTC
I am getting below exception . OS Version is 10.8

2013-03-22 15:31:27.906 JewelryBox[1562:707] An uncaught exception was raised
2013-03-22 15:31:27.907 JewelryBox[1562:707] **\* -[**NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]
2013-03-22 15:31:27.908 JewelryBox[1562:707](0   CoreFoundation                      0x00007fff876a2b06 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff908a13f0 objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff8763f8ec -[__NSArrayM objectAtIndex:] + 252
    3   JewelryBox                          0x00000001018bcb10 JewelryBox + 322320
    4   libdispatch.dylib                   0x00007fff8ffa3f01 _dispatch_call_block_and_release + 15
    5   libdispatch.dylib                   0x00007fff8ffa00b6 _dispatch_client_callout + 8
    6   libdispatch.dylib                   0x00007fff8ffa50c8 _dispatch_main_queue_callback_4CF + 275
    7   CoreFoundation                      0x00007fff87644b4c __CFRunLoopRun + 1644
    8   CoreFoundation                      0x00007fff876440e2 CFRunLoopRunSpecific + 290
    9   HIToolbox                           0x00007fff8490feb4 RunCurrentEventLoopInMode + 209
    10  HIToolbox                           0x00007fff8490fc52 ReceiveNextEventCommon + 356
    11  HIToolbox                           0x00007fff8490fae3 BlockUntilNextEventMatchingListInMode + 62
    12  AppKit                              0x00007fff89194563 _DPSNextEvent + 685
    13  AppKit                              0x00007fff89193e22 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 128
    14  AppKit                              0x00007fff893de639 -[NSApplication _realDoModalLoop:peek:] + 485
    15  AppKit                              0x00007fff893de8fe -[NSApplication runModalForWindow:] + 120
    16  Foundation                          0x00007fff8d007395 __NSFireDelayedPerform + 358
    17  CoreFoundation                      0x00007fff8765f804 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
    18  CoreFoundation                      0x00007fff8765f31d __CFRunLoopDoTimer + 557
    19  CoreFoundation                      0x00007fff87644ad9 __CFRunLoopRun + 1529
    20  CoreFoundation                      0x00007fff876440e2 CFRunLoopRunSpecific + 290
    21  HIToolbox                           0x00007fff8490feb4 RunCurrentEventLoopInMode + 209
    22  HIToolbox                           0x00007fff8490fb94 ReceiveNextEventCommon + 166
    23  HIToolbox                           0x00007fff8490fae3 BlockUntilNextEventMatchingListInMode + 62
    24  AppKit                              0x00007fff89194563 _DPSNextEvent + 685
    25  AppKit                              0x00007fff89193e22 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 128
    26  AppKit                              0x00007fff8918b1d3 -[NSApplication run] + 517
    27  AppKit                              0x00007fff8912fc06 NSApplicationMain + 869
    28  JewelryBox                          0x000000010186fbc4 JewelryBox + 7108
    29  ???                                 0x0000000000000001 0x0 + 1)
2013-03-22 15:31:27.910 JewelryBox[1562:707] **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00007fff876a2b06 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff908a13f0 objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff8763f8ec -[__NSArrayM objectAtIndex:] + 252
    3   JewelryBox                          0x00000001018bcb10 JewelryBox + 322320
    4   libdispatch.dylib                   0x00007fff8ffa3f01 _dispatch_call_block_and_release + 15
    5   libdispatch.dylib                   0x00007fff8ffa00b6 _dispatch_client_callout + 8
    6   libdispatch.dylib                   0x00007fff8ffa50c8 _dispatch_main_queue_callback_4CF + 275
    7   CoreFoundation                      0x00007fff87644b4c __CFRunLoopRun + 1644
    8   CoreFoundation                      0x00007fff876440e2 CFRunLoopRunSpecific + 290
    9   HIToolbox                           0x00007fff8490feb4 RunCurrentEventLoopInMode + 209
    10  HIToolbox                           0x00007fff8490fc52 ReceiveNextEventCommon + 356
    11  HIToolbox                           0x00007fff8490fae3 BlockUntilNextEventMatchingListInMode + 62
    12  AppKit                              0x00007fff89194563 _DPSNextEvent + 685
    13  AppKit                              0x00007fff89193e22 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 128
    14  AppKit                              0x00007fff893de639 -[NSApplication _realDoModalLoop:peek:] + 485
    15  AppKit                              0x00007fff893de8fe -[NSApplication runModalForWindow:] + 120
    16  Foundation                          0x00007fff8d007395 __NSFireDelayedPerform + 358
    17  CoreFoundation                      0x00007fff8765f804 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 20
    18  CoreFoundation                      0x00007fff8765f31d __CFRunLoopDoTimer + 557
    19  CoreFoundation                      0x00007fff87644ad9 __CFRunLoopRun + 1529
    20  CoreFoundation                      0x00007fff876440e2 CFRunLoopRunSpecific + 290
    21  HIToolbox                           0x00007fff8490feb4 RunCurrentEventLoopInMode + 209
    22  HIToolbox                           0x00007fff8490fb94 ReceiveNextEventCommon + 166
    23  HIToolbox                           0x00007fff8490fae3 BlockUntilNextEventMatchingListInMode + 62
    24  AppKit                              0x00007fff89194563 _DPSNextEvent + 685
    25  AppKit                              0x00007fff89193e22 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 128
    26  AppKit                              0x00007fff8918b1d3 -[NSApplication run] + 517
    27  AppKit                              0x00007fff8912fc06 NSApplicationMain + 869
    28  JewelryBox                          0x000000010186fbc4 JewelryBox + 7108
    29  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminate called throwing an exception
Abort trap: 6

**Comment by rguderlei** [comment] 2013-03-26 11:42
Same problem here. I could solve it by installing the XCode command line tools.
HTH

**Comment by remear** [comment] 2013-03-31 23:41
This appears to be a duplicate of #180 and should be resolved in v1.5. Caused by GCC not being found and throwing an index out of bounds error.

**Closed as completed by remear** 2013-03-31 23:41 UTC
