### ISSUE TITLE
Crash Report: Crash when selecting a gemset

### ISSUE THREAD

**Issue by sauy7** [remear/jewelrybox#40] opened 2011-09-22 15:05 UTC
I get the following crash report when selecting a gemset (under ruby 1.9.2p290):

9/22/11 4:59:39 PM  JewelryBox[25331]   An uncaught exception was raised
9/22/11 4:59:39 PM  JewelryBox[25331]   **\* -[NSCFArray objectAtIndex:]: index (2) beyond bounds (2)
9/22/11 4:59:39 PM  JewelryBox[25331]   **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[NSCFArray objectAtIndex:]: index (2) beyond bounds (2)'
**\* Call stack at first throw:
(
    0   CoreFoundation                      0x00007fff855997b4 __exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x00007fff84e0cf03 objc_exception_throw + 45
    2   CoreFoundation                      0x00007fff855995d7 +[NSException raise:format:arguments:] + 103
    3   CoreFoundation                      0x00007fff85599564 +[NSException raise:format:] + 148
    4   Foundation                          0x00007fff874e1d28 _NSArrayRaiseBoundException + 122
    5   Foundation                          0x00007fff87444e9d -[NSCFArray objectAtIndex:] + 75
    6   JewelryBox                          0x000000010000e4e6 0x0 + 4295025894
    7   libSystem.B.dylib                   0x00007fff84499d64 _dispatch_call_block_and_release + 15
    8   libSystem.B.dylib                   0x00007fff844782d1 _dispatch_worker_thread2 + 239
    9   libSystem.B.dylib                   0x00007fff84477c08 _pthread_wqthread + 353
    10  libSystem.B.dylib                   0x00007fff84477aa5 start_wqthread + 13
)
9/22/11 4:59:39 PM  [0x0-0x14e14e].com.unfiniti.JewelryBox[25331]   terminate called after throwing an instance of 'NSException'
9/22/11 4:59:39 PM  com.apple.launchd.peruser.501[198]([0x0-0x14e14e].com.unfiniti.JewelryBox[25331]) Job appears to have crashed: Abort trap
9/22/11 4:59:40 PM  ReportCrash[26202]  Saved crash report for JewelryBox[25331] version 1.0 (1.0) to /Volumes/Users/tim/Library/Logs/DiagnosticReports/JewelryBox_2011-09-22-165940_XXX.crash

This does not happen on every gemset I have. When listing gems for the troublesome gemset in the terminal I get this:

**\* LOCAL GEMS ***

abstract (1.0.0)
actionmailer (3.0.10, 3.0.7)
actionpack (3.0.10, 3.0.7)
activemodel (3.0.10, 3.0.7)
activerecord (3.0.10, 3.0.7)
activeresource (3.0.10, 3.0.7)
activesupport (3.0.10, 3.0.7)
addressable (2.2.6)
arel (2.0.10)
builder (2.1.2)
bundler (1.0.18)
capistrano (2.8.0)
capistrano-ext (1.2.1)
capybara (1.0.1)
childprocess (0.2.1)
ci_reporter (1.6.5, 1.6.4)
colored (1.2)
crack (0.1.8)
cucumber (1.0.2)
cucumber-rails (1.0.2, 0.5.2)
daemons (1.0.10)
diff-lcs (1.1.2)
erubis (2.6.6)
ffi (1.0.9)
fuubar (0.0.6)
gem_plugin (0.2.3)
gherkin (2.4.14, 2.4.6)
highline (1.6.2)
i18n (0.5.0)
json (1.5.3, 1.5.1)
json_pure (1.5.3)
launchy (2.0.5)
mail (2.2.19)
mime-types (1.16)
mocha (0.9.12)
mongrel (1.2.0.pre2)
net-scp (1.0.4)
net-sftp (2.0.5)
net-ssh (2.2.0, 2.1.4)
net-ssh-gateway (1.1.0)
nokogiri (1.5.0)
polyglot (0.3.2)
rack (1.2.3)
rack-mount (0.6.14)
rack-test (0.5.7)
rails (3.0.10, 3.0.7)
railties (3.0.10, 3.0.7)
rake (0.9.2, 0.8.7)
rcov (0.9.10, 0.9.9)
rdoc (3.9.2)
rest-client (1.6.3, 1.6.1)
rspec (2.6.0)
rspec-core (2.6.4, 2.6.3)
rspec-expectations (2.6.0)
rspec-instafail (0.1.8)
rspec-mocks (2.6.0)
rspec-rails (2.6.1)
ruby-progressbar (0.0.10)
rubyzip (0.9.4)
selenium-webdriver (2.4.0)
serviceplus (1.14.0.0)
spork (0.8.5)
term-ansicolor (1.0.6)
thor (0.14.6)
treetop (1.4.10)
tzinfo (0.3.29)
uuidtools (2.1.2)
webmock (1.7.4, 1.6.4)
wirble (0.1.3)
xpath (0.1.4)

This is the list of gems that does not cause a crash:

gem list

abstract (1.0.0)
actionmailer (3.0.7)
actionpack (3.0.7)
activemodel (3.0.7)
activerecord (3.0.7)
activeresource (3.0.7)
activesupport (3.0.7)
acts_as_tree (0.1.1)
archive-tar-minitar (0.5.2)
arel (2.0.10)
autotest-fsevent (0.2.5)
autotest-growl (0.2.9)
backports (2.2.1)
bcrypt-ruby (2.1.4)
brightcove-api (1.0.8)
bson (1.3.1)
bson_ext (1.3.1)
builder (2.1.2)
bundler (1.0.18)
cancan (1.6.5)
capybara (0.4.1.2)
celerity (0.8.9)
childprocess (0.1.9)
ci_reporter (1.6.4)
columnize (0.3.2)
configuration (1.2.0)
crack (0.1.8)
culerity (0.2.15)
daemons (1.1.3)
dalli (1.0.4)
delayed_job (2.1.4)
devise (1.3.4)
diff-lcs (1.1.2)
dimma (1.1.0)
erubis (2.6.6)
factory_girl (1.3.3)
ffi (1.0.9)
heroku (2.2.0)
hoptoad_notifier (2.4.10)
httparty (0.7.7)
i18n (0.5.0)
json (1.4.6)
json_pure (1.5.1)
launchy (0.4.0)
linecache19 (0.5.12)
mail (2.2.19)
mime-types (1.16)
mongo (1.3.1)
mongoid (2.0.2)
monkey-lib (0.5.4)
nokogiri (1.4.3.1)
orderedhash (0.0.6)
orm_adapter (0.0.5)
polyglot (0.3.1)
rack (1.2.3)
rack-cache (1.0.2)
rack-mount (0.6.14)
rack-test (0.5.7)
rails (3.0.7)
railties (3.0.7)
rake (0.9.2, 0.8.7)
rest-client (1.6.1)
rmagick (2.13.1)
rspec (2.6.0)
rspec-core (2.6.3)
rspec-expectations (2.6.0)
rspec-mocks (2.6.0)
rspec-rails (2.6.1)
ruby-debug-base19 (0.11.25)
ruby-debug19 (0.11.6)
ruby-prof (0.10.7)
ruby_core_source (0.1.5)
rubyzip (0.9.4)
selenium-webdriver (0.2.0)
shoulda-matchers (1.0.0.beta2)
simplecov (0.4.2)
simplecov-html (0.4.5)
simplecov-rcov (0.2.0)
sinatra (1.2.6)
sinatra-advanced-routes (0.5.1)
sinatra-reloader (0.5.0)
sinatra-sugar (0.5.1)
spork (0.8.4)
sqlite3 (1.3.3)
sqlite3-ruby (1.3.3)
sys-uname (0.8.5)
term-ansicolor (1.0.5)
test-unit (2.3.0)
thor (0.14.6)
tilt (1.3.1)
treetop (1.4.9)
tzinfo (0.3.27)
warden (1.0.4)
xpath (0.1.4)
ZenTest (4.5.0)

**Comment by sauy7** [comment] 2011-09-22 15:06
Forgot to say, this is running on OS X 10.6.8.

**Comment by ghost** [comment] 2011-09-22 20:19
Same crash on 10.7.1
rvm 1.8.3
JewelryBox v1 build 3558

**Comment by remear** [comment] 2011-10-21 17:52
The issue was caused by gems like rcov that have several authors listed. Gem lists them all but places a line return to split some onto a second line which did not coform the the parsing method used to extract the gem information.

This should be fixed for the 1.1 release.

**Closed as completed** 2011-10-29 18:52 UTC
Labels: Bug
